# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = I-IBM
QMAKE_CXXFLAGS += -std=c++17

# DESTDIR = ../bin
QT += core opengl widgets gui openglwidgets
CONFIG += debug c++17
DEFINES += _WINDOWS QT_LARGEFILE_SUPPORT QT_OPENGL_LIB _USE_MATH_DEFINES QT_DLL QT_HAVE_MMX QT_HAVE_3DNOW QT_HAVE_SSE QT_HAVE_MMXEXT QT_HAVE_SSE2
INCLUDEPATH += ./src \
#    ../../../../../../Program Files/Microsoft SDKs/Kinect/v2.0-DevPreview1404/inc \
    $(QTDIR)/mkspecs/default \
    ./ \
    "C:/Qt/Qt5.8.0/5.8/msvc2015_64/include" \
    ./GeneratedFiles \
    ./include 

LIBS += -L"./lib" \
    -L"C:/Qt/Qt5.8.0/5.8/msvc2015_64/lib" \
    -L"./src/OpenMesh/lib" \
    -lopencv_core248d \
    -lopencv_highgui248d \
    -lopencv_imgproc248d \
    -lOpenMeshCored \
    -lOpenMeshToolsd
#    -l"C:/ProgramFiles/Microsoft SDKs/Kinect/v2.0-DevPreview1404/lib/x64/Kinect20"
# DEPENDPATH += $$PWD/.
MOC_DIR = $$PWD/GeneratedFiles
OBJECTS_DIR += debug
UI_DIR = $$PWD/GeneratedFiles
RCC_DIR = $$PWD/GeneratedFiles
include($$PWD/I-IBM.pri)


 HEADERS += \
# ./src/VisionWidget/VisionWidget.h \
     ./src/GLWidget/GLOptionWidget.h \
     ./globals.h \
     ./src/GLWidget/GLWidget.h \
     ./src/Geometry3D/Geometry3D.h \
    ./src/Logview/logviewdockwidget.h \
    ./mainwindow.h
#    ./KinectOptionWidget.h \
 ./src/NR/EigenSolver.h \
 ./src/NR/kdtree.h \
 ./src/NR/MatrixEq.h \
 ./src/NR/NR.h \
 ./src/NR/nr3.h \
 ./src/NR/NR_EigenJacobi.h \
 ./src/NR/NR_Matrix.h \
 ./src/NR/pointbox.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Cube.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/define.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Edge.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Graph.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Kruskal.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/MarchingCubes.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Node.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nr.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrtypes.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrtypes_nr.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrutil.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrutil_nr.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/ply.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Point.h \
 ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Vector3f.h \
./src/MemoryLeakDetector/DebugNew.h \
./src/MemoryLeakDetector/MemoryLeak.h \
#    ./src/Kinect/KinectBasic.h \
#    ./src/Kinect/Mode.h \
#    ./src/Kinect/NLMFilter.h
 SOURCES += \
 ./globals.cpp \
     ./src/GLWidget/GLOptionWidget.cpp \
     ./src/GLWidget/GLWidget.cpp \
     ./src/Geometry3D/Geo3DMesh.cpp \
    ./src/Logview/logviewdockwidget.cpp \
    ./main.cpp \
    ./mainwindow.cpp
    ./src/Point/Geo3DPoint.cpp \
    ./src/VisionWidget/VisionWidget.cpp \
    ./src/NR/EigenSolver.cpp \
    ./src/NR/MatrixEq.cpp \
    ./src/NR/NR.cpp \
    ./src/NR/NR_EigenJacobi.cpp \
    ./src/NR/NR_Matrix.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Cube.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/define.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Edge.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/eigsrt.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Graph.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/jacobi.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Kruskal.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/MarchingCubes.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Node.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/plyfile.c \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Point.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Vector3f.cpp \
   ./src/MemoryLeakDetector/DebugNew.cpp \
   ./src/MemoryLeakDetector/MemoryLeak.cpp \
#    ./src/Kinect/KinectBasic.cpp \
#    ./src/Kinect/Mode.cpp \
#    ./src/Kinect/NLMFilter.cpp \
#    ./KinectOptionWidget.cpp
RESOURCES += IIBM.qrc
