# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = I-IBM
DESTDIR = ../Debug
QT += core opengl axserver axcontainer widgets gui
CONFIG += debug
DEFINES += _WINDOWS QT_LARGEFILE_SUPPORT QT_OPENGL_LIB _USE_MATH_DEFINES QT_DLL QT_HAVE_MMX QT_HAVE_3DNOW QT_HAVE_SSE QT_HAVE_MMXEXT QT_HAVE_SSE2
INCLUDEPATH += ./src \
    ../../../../../../../Program Files/Microsoft SDKs/Kinect/v2.0-DevPreview1404/inc \
    $(QTDIR)/mkspecs/default \
    . \
    ./GeneratedFiles \
    ../../../../../../../opencv/build/include \
    ./src/EmbeddedDeform \
    ./GeneratedFiles/Debug
LIBS += -L"./lib" \
    -L"../../../../../../../opencv/build/x64/vc11/lib" \
    -L"./lib/x64" \
    -lopencv_core249d \
    -lopencv_highgui249d \
    -lopencv_imgproc249d \
    -llibOpenMeshCored \
    -l"C:/Program \
    -lFiles/Microsoft \
    -lSDKs/Kinect/v2.0-DevPreview1404/lib/x64/Kinect20" \
    -lopengl32 \
    -lglu32
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(I-IBM.pri)
win32:RC_FILE = I-IBM.rc
