# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/Kinect/Mode.h \
    ./src/Kinect/NLMFilter.h \
    ./src/Kinect/Microsoft_grabber2.h \
    ./src/MemoryLeakDetector/DebugNew.h \
    ./src/MemoryLeakDetector/MemoryLeak.h \
    ./src/VisionWidget/VisionWidget.h \
    ./src/GLWidget/GLOptionWidget.h \
    ./globals.h \
    ./src/GLWidget/GLWidget.h \
    ./src/Geometry3D/Geometry3D.h \
    ./src/Logview/logviewdockwidget.h \
    ./mainwindow.h \
    ./KinectOptionWidget.h \
    ./resource.h \
    ./ui_KinectOptionWidget.h \
    ./DeformationWidget.h \
    ./src/NR/EigenSolver.h \
    ./src/NR/kdtree.h \
    ./src/NR/MatrixEq.h \
    ./src/NR/NR.h \
    ./src/NR/nr3.h \
    ./src/NR/NR_EigenJacobi.h \
    ./src/NR/NR_Matrix.h \
    ./src/NR/pointbox.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Cube.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/define.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Edge.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Graph.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Kruskal.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/MarchingCubes.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Node.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nr.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrtypes.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrtypes_nr.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrutil.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/nrutil_nr.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/ply.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Point.h \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Vector3f.h \
    ./CorrespondenceOpenCV.h \
    ./src/EmbeddedDeform/uniform_triangulation.h \
    ./src/EmbeddedDeform/debugtrace.h \
    ./src/EmbeddedDeform/DeformableMesh3d.h \
    ./src/EmbeddedDeform/DeformationGraph.h \
    ./src/EmbeddedDeform/GaussNewtonSolver.h \
    ./src/EmbeddedDeform/genGraphDialog.h \
    ./src/EmbeddedDeform/math/matrix3d.h \
    ./src/EmbeddedDeform/math/point3d.h \
    ./src/EmbeddedDeform/math/SparseMatrix.h \
    ./src/EmbeddedDeform/math/vector3d.h
SOURCES += ./src/Kinect/Microsoft_grabber2.cpp \
    ./src/Kinect/Mode.cpp \
    ./src/Kinect/NLMFilter.cpp \
    ./src/MemoryLeakDetector/DebugNew.cpp \
    ./src/MemoryLeakDetector/MemoryLeak.cpp \
    ./src/NR/EigenSolver.cpp \
    ./src/NR/MatrixEq.cpp \
    ./src/NR/NR.cpp \
    ./src/NR/NR_EigenJacobi.cpp \
    ./src/NR/NR_Matrix.cpp \
    ./DeformationWidget.cpp \
    ./globals.cpp \
    ./KinectOptionWidget.cpp \
    ./src/GLWidget/GLOptionWidget.cpp \
    ./src/GLWidget/GLWidget.cpp \
    ./src/Geometry3D/Geo3DMesh.cpp \
    ./src/Logview/logviewdockwidget.cpp \
    ./main.cpp \
    ./mainwindow.cpp \
    ./src/Point/Geo3DPoint.cpp \
    ./src/VisionWidget/VisionWidget.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Cube.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/define.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Edge.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/eigsrt.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Graph.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/jacobi.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Kruskal.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/MarchingCubes.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Node.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/plyfile.c \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Point.cpp \
    ./src/PBM/ImpicitSurfaceReconstruction/MarchingCubes/Vector3f.cpp \
    ./CorrespondenceOpenCV.cpp \
    ./src/EmbeddedDeform/DeformableMesh3d.cpp \
    ./src/EmbeddedDeform/DeformationGraph.cpp \
    ./src/EmbeddedDeform/GaussNewtonSolver.cpp \
    ./src/EmbeddedDeform/genGraphDialog.cpp \
    ./src/EmbeddedDeform/uniform_triangulation.cpp
FORMS += ./KinectOptionWidget.ui \
    ./DeformationWidget.ui
RESOURCES += IIBM.qrc
